---
# tasks file for openbao agent

- name: agent | Ensure agent config directory exists
  ansible.builtin.file:
    path: "{{ openbao_agent_config_path | dirname }}"
    state: directory
    owner: openbao
    group: openbao
    mode: "0750"

- name: agent | Ensure agent runtime directory exists
  ansible.builtin.file:
    path: /opt/openbao
    state: directory
    owner: openbao
    group: openbao
    mode: "0750"

- name: agent | Configure OpenBao agent
  ansible.builtin.template:
    src: openbao-agent.hcl.j2
    dest: "{{ openbao_agent_config_path }}"
    owner: openbao
    group: openbao
    mode: "0600"
  notify:
    - Restart OpenBao Agent

- name: agent | Configure OpenBao agent environment file
  ansible.builtin.template:
    src: openbao-agent.env.j2
    dest: "{{ openbao_agent_env_path }}"
    owner: openbao
    group: openbao
    mode: "0600"
  when:
    - openbao_agent_environment | length > 0
  notify:
    - Restart OpenBao Agent

- name: agent | Configure OpenBao agent systemd unit
  ansible.builtin.template:
    src: openbao-agent.service.j2
    dest: /etc/systemd/system/openbao-agent.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart OpenBao Agent

- name: agent | Manage OpenBao agent service
  ansible.builtin.systemd:
    name: openbao-agent
    state: started
    enabled: true
    daemon_reload: true
