---

- name: assert | Test openbao_version
  ansible.builtin.assert:
    that:
      - openbao_version is defined
      - openbao_version is string
      - openbao_version | length > 0
    quiet: true

- name: assert | Test openbao_download_dir
  ansible.builtin.assert:
    that:
      - openbao_download_dir is defined
      - openbao_download_dir is string
      - openbao_download_dir | length > 0
    quiet: true

- name: assert | Test openbao_validate_certs
  ansible.builtin.assert:
    that:
      - openbao_validate_certs is defined
      - openbao_validate_certs is boolean
    quiet: true
